sonar.projectKey=MiguelCiav_sistema-de-gestion-automatizado-izt
sonar.organization=miguelciav

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/test/**,dist/**,coverage/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
